const ADD_SERVICE = 'ADD_SERVICE';
const REMOVE_SERVICE = 'REMOVE_SERVICE';
const EDIT_SERVICE = 'EDIT_SERVICE';
const FILTER_SERVICE = 'FILTER_SERVICE';
const INITIAL_SERVICE = 'INITIAL_SERVICE';
const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
const CLEAR_SERVICE_FIELD = 'CLEAR_SERVICE_FIELD';
const EDIT_SERVICE_FIELD = 'EDIT_SERVICE_FIELD';

export {
   ADD_SERVICE,
   REMOVE_SERVICE,
   EDIT_SERVICE,
   FILTER_SERVICE,
   INITIAL_SERVICE,
   CHANGE_SERVICE_FIELD,
   CLEAR_SERVICE_FIELD,
   EDIT_SERVICE_FIELD,
};
