const ADD_SERVICE = 'ADD_SERVICE';
const REMOVE_SERVICE = 'REMOVE_SERVICE';
const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
const CLEAR_SERVICE_FIELD = 'CLEAR_SERVICE_FIELD';
const EDIT_SERVICE_FIELD = 'EDIT_SERVICE_FIELD';

export {
   ADD_SERVICE,
   REMOVE_SERVICE,
   CHANGE_SERVICE_FIELD,
   CLEAR_SERVICE_FIELD,
   EDIT_SERVICE_FIELD,
};
